all:
	g++ -I ../ main.cpp stonks.cpp ../item.cpp -lSDL2 -lSDL2main -lSDL2_image -lSDL2_net -lSDL2_ttf 
scroller:
	g++ -I ../ -lSDL2 -lSDL2_image -lSDL2_net -lSDL2_ttf scroller.cpp ../item.cpp

bigShort:
	g++ -I ../ -lSDL2 -lSDL2_image -lSDL2_net -lSDL2_ttf bigShort.cpp stonks.cpp ../item.cpp
